# ─────────────────────────────────────────────────────────────────
# Agent Adam — k3s Cluster Bootstrap Module
# SilverTech | June 2026
#
# Automates k3s installation, monitoring stack, and essential
# operators on Hetzner Cloud servers provisioned by main.tf.
# Uses cloud-init for first-boot automation.
# ─────────────────────────────────────────────────────────────────

# ─── Cloud-Init: API Server (k3s master node) ────────────────────
resource "local_file" "cloud_init_api" {
  filename = "${path.module}/generated/cloud-init-api-${var.environment}.yml"
  content = templatefile("${path.module}/templates/cloud-init-api.yml.tpl", {
    environment            = var.environment
    project_name           = var.project_name
    k3s_token              = random_password.k3s_token.result
    postgres_version       = var.postgres_version
    redis_version          = var.redis_version
    enable_monitoring      = var.enable_monitoring
    grafana_admin_password = var.grafana_admin_password
    alert_email            = var.alert_email
    data_retention_days    = var.data_retention_days
    hetzner_region         = "fsn1"

    # API keys (from vault / GitHub secrets at apply time)
    deepgram_api_key    = var.deepgram_api_key
    gemini_api_key      = var.gemini_api_key
    openai_api_key      = var.openai_api_key
    twilio_account_sid  = var.twilio_account_sid
    twilio_auth_token   = var.twilio_auth_token
    sendgrid_api_key    = var.sendgrid_api_key
    supabase_url        = var.supabase_url
    supabase_anon_key   = var.supabase_anon_key
    supabase_service_key = var.supabase_service_key
  })
}

# ─── Cloud-Init: Worker Node ─────────────────────────────────────
resource "local_file" "cloud_init_worker" {
  filename = "${path.module}/generated/cloud-init-worker-${var.environment}.yml"
  content = templatefile("${path.module}/templates/cloud-init-worker.yml.tpl", {
    environment  = var.environment
    project_name = var.project_name
    k3s_token    = random_password.k3s_token.result
    k3s_master_ip = hcloud_server.api.network[0].ip
  })
}

# ─── k3s Cluster Token ───────────────────────────────────────────
resource "random_password" "k3s_token" {
  length  = 48
  special = false
}

# ─── k3s Master Node (API server) ─────────────────────────────────
resource "hcloud_server" "api" {
  name        = "${var.project_name}-api-${var.environment}"
  image       = "ubuntu-24.04"
  server_type = var.api_server_type
  datacenter  = "fsn1-dc14"
  location    = "fsn1"

  ssh_keys     = [hcloud_ssh_key.default.id]
  firewall_ids = [hcloud_firewall.api.id]

  network {
    network_id = hcloud_network.main.id
  }

  public_net {
    ipv4_enabled = true
    ipv6_enabled = true
  }

  labels = {
    environment = var.environment
    role        = "k3s-master"
    managed_by  = "terraform"
  }

  user_data = local_file.cloud_init_api.content

  depends_on = [hcloud_network_subnet.backend]
}

# ─── k3s Worker Nodes ────────────────────────────────────────────
resource "hcloud_server" "worker" {
  count       = var.worker_server_count
  name        = "${var.project_name}-worker-${count.index + 1}-${var.environment}"
  image       = "ubuntu-24.04"
  server_type = var.worker_server_type
  datacenter  = "fsn1-dc14"
  location    = "fsn1"

  ssh_keys     = [hcloud_ssh_key.default.id]
  firewall_ids = [hcloud_firewall.api.id]

  network {
    network_id = hcloud_network.main.id
  }

  public_net {
    ipv4_enabled = true
    ipv6_enabled = true
  }

  labels = {
    environment = var.environment
    role        = "k3s-worker"
    managed_by  = "terraform"
  }

  user_data = local_file.cloud_init_worker.content
}

# ─── Cloud-Init Template: API (k3s server) ───────────────────────
resource "local_file" "cloud_init_api_template" {
  filename = "${path.module}/templates/cloud-init-api.yml.tpl"
  content  = <<-EOF
#cloud-config
# Agent Adam — k3s Master Node Bootstrap
# Auto-generated by Terraform — do not edit manually

hostname: ${project_name}-api
timezone: Europe/Warsaw

# ─── System packages ──────────────────────────────────────────
packages:
  - curl
  - wget
  - git
  - jq
  - ufw
  - fail2ban
  - ca-certificates
  - gnupg
  - lsb-release
  - software-properties-common

# ─── Security hardening ────────────────────────────────────────
write_files:
  - path: /etc/sysctl.d/99-k8s.conf
    content: |
      net.bridge.bridge-nf-call-iptables = 1
      net.bridge.bridge-nf-call-ip6tables = 1
      net.ipv4.ip_forward = 1
      vm.swappiness = 0
      vm.overcommit_memory = 1
      kernel.panic = 10
      kernel.panic_on_oops = 1

  - path: /etc/security/limits.d/99-nofile.conf
    content: |
      * soft nofile 65536
      * hard nofile 65536

  - path: /var/lib/rancher/k3s/server/manifests/agent-adam-namespace.yaml
    permissions: '0644'
    content: |
      apiVersion: v1
      kind: Namespace
      metadata:
        name: agent-adam
        labels:
          app: agent-adam
          environment: ${environment}

  - path: /var/lib/rancher/k3s/server/manifests/monitoring-namespace.yaml
    permissions: '0644'
    content: |
      apiVersion: v1
      kind: Namespace
      metadata:
        name: monitoring
        labels:
          app: monitoring

# ─── k3s install ───────────────────────────────────────────────
runcmd:
  # Enable kernel modules
  - modprobe overlay
  - modprobe br_netfilter
  - sysctl --system

  # Configure firewall
  - ufw allow 22/tcp comment 'SSH'
  - ufw allow 80/tcp comment 'HTTP'
  - ufw allow 443/tcp comment 'HTTPS'
  - ufw allow 6443/tcp comment 'k3s API'
  - ufw --force enable

  # Install k3s server (embedded etcd)
  - |
    curl -sfL https://get.k3s.io | INSTALL_K3S_EXEC="
      --cluster-init
      --write-kubeconfig-mode 644
      --tls-san=${hcloud_floating_ip.api.ip_address}
      --tls-san=api.silvertech.ai
      --disable traefik
      --disable servicelb
      --node-label environment=${environment}
      --node-label role=master
      --kubelet-arg max-pods=110
      --kube-apiserver-arg enable-admission-plugins=PodSecurityPolicy,NodeRestriction
      --etcd-expose-metrics true
    " sh -

  # Wait for k3s to be ready
  - sleep 30
  - kubectl wait --for=condition=Ready nodes --all --timeout=300s

  # Install Helm
  - curl https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3 | bash

  # Install cert-manager
  - |
    helm repo add jetstack https://charts.jetstack.io
    helm repo update
    helm upgrade --install cert-manager jetstack/cert-manager \
      --namespace cert-manager --create-namespace \
      --set installCRDs=true \
      --set global.leaderElection.namespace=cert-manager \
      --wait

  # Create Let's Encrypt ClusterIssuer
  - |
    kubectl apply -f - <<ISSUER
    apiVersion: cert-manager.io/v1
    kind: ClusterIssuer
    metadata:
      name: letsencrypt-prod
    spec:
      acme:
        server: https://acme-v02.api.letsencrypt.org/directory
        email: ${alert_email}
        privateKeySecretRef:
          name: letsencrypt-prod-account-key
        solvers:
          - http01:
              ingress:
                class: nginx
    ISSUER

  # Install NGINX Ingress Controller
  - |
    helm upgrade --install ingress-nginx ingress-nginx \
      --repo https://kubernetes.github.io/ingress-nginx \
      --namespace ingress-nginx --create-namespace \
      --set controller.metrics.enabled=true \
      --set controller.service.externalTrafficPolicy=Local \
      --set controller.replicaCount=2 \
      --set controller.autoscaling.enabled=true \
      --set controller.autoscaling.minReplicas=2 \
      --set controller.autoscaling.maxReplicas=5 \
      --wait

  %{ if enable_monitoring }
  # Install Prometheus stack
  - |
    helm repo add prometheus-community https://prometheus-community.github.io/helm-charts
    helm repo update
    helm upgrade --install kube-prometheus prometheus-community/kube-prometheus-stack \
      --namespace monitoring --create-namespace \
      --set grafana.adminPassword=${grafana_admin_password} \
      --set grafana.ingress.enabled=true \
      --set grafana.ingress.hosts[0]=admin.silvertech.ai \
      --set grafana.ingress.tls[0].hosts[0]=admin.silvertech.ai \
      --set grafana.ingress.tls[0].secretName=grafana-tls \
      --set prometheus.retention=30d \
      --set prometheus.storage.size=50Gi \
      --set alertmanager.ingress.enabled=false \
      --wait
  %{ endif }

  # Install Redis (for BullMQ + caching)
  - |
    kubectl apply -f - <<REDIS
    apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: redis
      namespace: agent-adam
    spec:
      replicas: 1
      selector:
        matchLabels:
          app: redis
      template:
        metadata:
          labels:
            app: redis
        spec:
          containers:
            - name: redis
              image: redis:${redis_version}-alpine
              ports:
                - containerPort: 6379
              resources:
                requests:
                  cpu: 100m
                  memory: 128Mi
                limits:
                  cpu: 500m
                  memory: 512Mi
              args:
                - --maxmemory 512mb
                - --maxmemory-policy allkeys-lru
                - --save 900 1
                - --save 300 10
    ---
    apiVersion: v1
    kind: Service
    metadata:
      name: redis
      namespace: agent-adam
    spec:
      selector:
        app: redis
      ports:
        - port: 6379
    REDIS

  # Output k3s token for worker join
  - echo "K3S_TOKEN=${k3s_token}" > /root/k3s_join_info.txt
  - echo "✅ k3s master bootstrap complete"

final_message: "Agent Adam k3s master bootstrapped in $UPTIME seconds"
EOF
}

# ─── Cloud-Init Template: Worker ─────────────────────────────────
resource "local_file" "cloud_init_worker_template" {
  filename = "${path.module}/templates/cloud-init-worker.yml.tpl"
  content  = <<-EOF
#cloud-config
# Agent Adam — k3s Worker Node Bootstrap

hostname: ${project_name}-worker
timezone: Europe/Warsaw

packages:
  - curl
  - wget
  - ufw
  - fail2ban

runcmd:
  - modprobe overlay
  - modprobe br_netfilter
  - sysctl --system

  - ufw allow 22/tcp
  - ufw --force enable

  # Join as k3s agent
  - |
    curl -sfL https://get.k3s.io | K3S_URL=https://${k3s_master_ip}:6443 \
      K3S_TOKEN=${k3s_token} \
      INSTALL_K3S_EXEC="
        --node-label environment=${environment}
        --node-label role=worker
        --kubelet-arg max-pods=50
      " sh -

  - sleep 15
  - echo "✅ k3s worker joined cluster"

final_message: "Agent Adam k3s worker joined in $UPTIME seconds"
EOF
}

# ─── Outputs ─────────────────────────────────────────────────────
output "k3s_master_ip" {
  value       = hcloud_server.api.network[0].ip
  description = "k3s master internal IP (for worker join)"
}

output "k3s_token" {
  value       = random_password.k3s_token.result
  sensitive   = true
  description = "k3s cluster join token"
}

output "kubeconfig_command" {
  value       = "ssh root@${hcloud_floating_ip.api.ip_address} 'cat /etc/rancher/k3s/k3s.yaml' > ~/.kube/agent-adam-config"
  description = "Command to fetch kubeconfig from master node"
}

output "grafana_url" {
  value       = "https://admin.silvertech.ai"
  description = "Grafana dashboard URL"
}

output "api_endpoint" {
  value       = "https://api.silvertech.ai"
  description = "Agent Adam API endpoint"
}

output "nodes" {
  value = {
    master = {
      name = hcloud_server.api.name
      public_ip  = hcloud_server.api.ipv4_address
      private_ip = hcloud_server.api.network[0].ip
      type = hcloud_server.api.server_type
    }
    workers = [for i, w in hcloud_server.worker : {
      name = w.name
      public_ip  = w.ipv4_address
      private_ip = w.network[0].ip
      type = w.server_type
    }]
  }
  description = "All cluster node details"
}
